### ISSUE TITLE
【依頼】フリマアプリ挙動確認

### ISSUE THREAD

**Issue by maradonamania** [maradonamania/furima-36256#21]
https://furima-36256.herokuapp.com/
test@sample     testpass1
test1@sample   testpass2

**Comment by takumi0530** [comment]
@maradonamania さん、お待たせいたしました。ご提出ありがとうございます‼︎
動作の確認をしたところ、修正していただきたい箇所がございました。
以下のご確認をお願いします！

### **[修正依頼箇所]**

- [ ] **カテゴリーは、「---、メンズ、レディース、ベビー・キッズ、インテリア・住まい・小物、本・音楽・ゲーム、おもちゃ・ホビー・グッズ、家電・スマホ・カメラ、スポーツ・レジャー、ハンドメイド、その他」の11項目が表示されること（--- は初期値として設定すること）**
「、」が入ってしまっていました。
<img width="374" alt="スクリーンショット 2021-08-02 14 46 12" src="https://user-images.githubusercontent.com/76197191/127810395-66b6e0d4-6cde-4667-a282-521857eeaa97.png">


- [x] **商品詳細表示ページは、ログイン状況や商品の販売状況に関係なく、誰でも見ることができること**
ログアウト状態ですと閲覧できますが、出品者・ログイン状態のユーザーですとエラーページに遷移してしまいます。
**※上記により、ユーザー管理機能・商品出品機能の以外の動作確認ができておりません。次回ご提出時に確認させていただきます。**

<img width="581" alt="スクリーンショット 2021-08-02 14 43 03" src="https://user-images.githubusercontent.com/76197191/127810357-af4707d3-6349-40ca-9c2b-1a533fb809e8.png">


修正が完了しましたら、再度以下の最終課題完了報告フォームのご提出をお願いします！
※新しいissueを作っていただく必要はございません。
https://forms.gle/dYuR1wjeHepbEhU7A

**Comment by maradonamania** [comment]
指摘箇所修正しました。

**Comment by snkw-works** [comment]
@maradonamania さん、お待たせいたしました。ご提出ありがとうございます‼︎
動作の確認をしたところ、修正していただきたい箇所がございました。
以下、ご確認をお願いします！

[修正依頼箇所]
- [x] **商品詳細ページにて、商品出品時に登録した情報（商品名・商品画像・販売価格・配送料負担・商品説明・出品者名・カテゴリー・商品の状態・発送元の地域・発送日の目安）が、見本アプリと同様の形で出力されるよう修正しましょう**
「発送日の目安」欄に「配送料の負担」が表示されています。
<img width="416" alt="スクリーンショット 2021-08-02 16 29 26" src="https://user-images.githubusercontent.com/54050089/127821359-4c052981-ee6b-4971-b117-f966573584d5.png">

- [x] **ログイン状態の場合でも、自身が出品した売却済み商品の商品情報編集ページへ遷移しようとすると、トップページに遷移するよう修正しましょう**
売却済み商品の商品情報編集ページへ遷移できてしまいます。

- [x] **ログイン状態の場合にのみ、自身が出品した商品情報を削除できるよう修正しましょう**
削除ボタンをクリックすると、エラー画面に遷移してしまいます。
<img width="725" alt="スクリーンショット 2021-08-02 16 38 43" src="https://user-images.githubusercontent.com/54050089/127822352-1f465f76-ccab-4672-9bdf-1fe1e655e824.png">

修正が完了しましたら、再度以下の最終課題完了報告フォームのご提出をお願いします！
※新しいissueを作っていただく必要はございません。
https://forms.gle/dYuR1wjeHepbEhU7A

**Comment by snkw-works** [comment]
@maradonamania さん、お待たせいたしました。ご提出ありがとうございます‼︎
修正が確認でき、問題なく正常に動作することが確認できました！　**LGTM**です✨　
おめでとうございます🎉
着実に技術力が身につき、実用的なアプリになってきてますね（^^）
最終課題発表会では、今までの成果を十分に発揮することができるよう、私達も応援しております🍀

**※確認したのは必須機能のみです。追加実装した機能については確認しておりません。
そのため追加機能を実装している場合は、正しく想定通りの挙動であるか、再度ご自身でご確認をお願い致します。**
![最終課題終了_おめでとう画像_new1](https://user-images.githubusercontent.com/54050089/127941930-4f737803-955a-4e95-800c-53229675ad8d.png)
